// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityTuitionPaymentSystemApi.Models;

#nullable disable

namespace UniversityTuitionPaymentSystemApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240415084524_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityTuitionPaymentSystemApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000f,
                            PaymentDate = new DateTime(2024, 4, 15, 8, 45, 22, 810, DateTimeKind.Utc).AddTicks(8828),
                            StudentId = 1,
                            Term = "1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2000f,
                            PaymentDate = new DateTime(2024, 4, 15, 8, 45, 22, 810, DateTimeKind.Utc).AddTicks(8831),
                            StudentId = 2,
                            Term = "1"
                        });
                });

            modelBuilder.Entity("UniversityTuitionPaymentSystemApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudentNumber = "S12345"
                        },
                        new
                        {
                            Id = 2,
                            StudentNumber = "S67890"
                        });
                });

            modelBuilder.Entity("UniversityTuitionPaymentSystemApi.Models.Tuition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Tuitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000f,
                            StudentId = 1,
                            Term = "1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 4000f,
                            StudentId = 2,
                            Term = "1"
                        });
                });

            modelBuilder.Entity("UniversityTuitionPaymentSystemApi.Models.Payment", b =>
                {
                    b.HasOne("UniversityTuitionPaymentSystemApi.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityTuitionPaymentSystemApi.Models.Tuition", b =>
                {
                    b.HasOne("UniversityTuitionPaymentSystemApi.Models.Student", "Student")
                        .WithMany("Tuitions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityTuitionPaymentSystemApi.Models.Student", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Tuitions");
                });
#pragma warning restore 612, 618
        }
    }
}
